%YAML:1.0

number_x_square: 5
number_y_square: 5
#number_x_square_per_board: [5,5]
#number_y_square_per_board: [5,5]
resolution_x: 1500          # horizontal resolution in pixel
resolution_y: 1500          # vertical resolution in pixel
length_square: 0.04        # parameters on the marker (can be kept as it is)
length_marker: 0.03       # parameters on the marker (can be kept as it is)
number_board: 4
boards_index: [0, 1, 2, 3]           # leave it empty [] if the board index are ranging from zero to number_board; example of usage boards_index: [5,10] <-- only two board with index 5/10
#square_size: 0.037         # size of each square of the board in cm/mm/whatever 
